# Generated by Django 4.2.1 on 2023-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitlab_pid', models.IntegerField()),
                ('project_name', models.CharField(max_length=255)),
                ('parents', models.ManyToManyField(related_name='related_repository_repository', to='pipeman.repository')),
            ],
        ),
    ]
