# Generated by Django 4.2.1 on 2023-05-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_repository_repository', to='pipeman.repository'),
        ),
    ]
