# Generated by Django 4.2.1 on 2023-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeman', '0003_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='repository',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='related_repository_repository', to='pipeman.repository'),
        ),
    ]
