# Generated by Django 4.2.1 on 2023-06-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeman', '0005_repository_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='gitlab_pid',
            field=models.IntegerField(unique=True),
        ),
    ]
