# Generated by Django 4.2.1 on 2023-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pipeman", "0008_repository_last_commit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="last_commit",
        ),
    ]
